version: '3.8'

networks:
  fin-network:
    driver: bridge
    external: true


services:
  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "${RABBIT_WEB_PORT}:15672"  # Порт для веб-интерфейса
      - "${RABBIT_AMQP_PORT}:5672"   # Порт для AMQP
    environment:
      RABBITMQ_DEFAULT_USER: user  # Задайте имя пользователя
      RABBITMQ_DEFAULT_PASS: password  # Задайте пароль
    volumes:
      - ./docker/rabbitmq_data:/var/lib/rabbitmq
