global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'fin_fundamentals'
    static_configs:
      - targets: ['localhost:8090','host.docker.internal:8090']
  - job_name: 'fin_quotes'
    static_configs:
      - targets: [ 'localhost:8091', 'host.docker.internal:8091' ]
  - job_name: 'fin_api_gateway'
    static_configs:
      - targets: [ 'localhost:8092', 'host.docker.internal:8092' ]
  - job_name: 'fin_data_processing'
    static_configs:
      - targets: [ 'localhost:8093', 'host.docker.internal:8093' ]
  - job_name: 'fin_notifications'
    static_configs:
      - targets: [ 'localhost:8094', 'host.docker.internal:8094' ]
